spring.application.name: learn-german-with-ansk98

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn-german-with-ansk98-db
    username: ${db-username}
    password: ${db-password}

commands:
  command-definition:
    - path: /profile
      parameters:
        - key: name
          prompt: please write your name
        - key: surname
          prompt: please write your surname
        - key: age
          prompt: please write your age
    - path: /new-word
      with-navigation: true
      parameters:
        - key: word
          prompt: write a new word
        - key: translation
          prompt: write a translation
        - key: meaning
          prompt: what does this word mean?
        - key: forms
          prompt: write any forms of this word separated by |
        - key: frequency
          prompt: how frequent is this word
        - key: example
          prompt: give me an example
        - key: example-translation
          prompt: write translation for the example

bot:
  user:
  token: '6925832793:AAFDt_BI3-3Olw6iqrvuYczCvwKgDk5Qx1w'

