spring.application.name: learn-german-with-ansk98

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn-german-with-ansk98-db
    username: ${db-username}
    password: ${db-password}

commands:
  command-definition:
    - path: /new_word
      with-navigation: true
      parameters:
        - key: word
          required: true
          prompt: write a new word
        - key: translation
          required: true
          prompt: write a translation
        - key: meaning
          prompt: what does this word mean?
        - key: forms
          prompt: write any forms of this word separated by . without spaces
        - key: frequency
          prompt: how frequent is this word
        - key: example
          prompt: give me an example
        - key: example-translation
          prompt: write translation for the example
    - path: /current_words
    - path: /delete_word
      parameters:
        - key: word_reference
          prompt: please provide a unique word reference
    - path: /preview

bot:
  user:
  token: '6925832793:AAFDt_BI3-3Olw6iqrvuYczCvwKgDk5Qx1w'

