spring.application.name: learn-german-with-ansk98

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn-german-with-ansk98-db
    username: ${db-username}
    password: ${db-password}

commands:
  command-definition:
    - path: /new_word
      with-navigation: true
      parameters:
        - key: word
          required: true
          prompt: write a new word
        - key: translation
          required: true
          prompt: write a translation
        - key: meaning
          prompt: what does this word mean?
        - key: forms
          prompt: write any forms of this word separated by . without spaces
        - key: frequency
          prompt: how frequent is this word
        - key: example
          prompt: give me an example
        - key: example_translation
          prompt: write translation for the example
    - path: /cached_words
    - path: /delete_word
      parameters:
        - key: word_reference
          prompt: please provide a unique word reference
    - path: /preview_word_card
    - path: /generate_reading_exercise
      parameters:
        - key: level
          prompt: please enter the level of the text based on the CEFR level
        - key: topic
          prompt: please provide the topic of the text
    - path: /create_reading_exercise
      parameters:
        - key: text
          prompt: please provide a text to create reading exercise for
    - path: /cached_reading_exercise

bot:
  user:
  token: '6925832793:AAFDt_BI3-3Olw6iqrvuYczCvwKgDk5Qx1w'

ai:
  params:
    token: ${ai-token}
    model: gpt-4o-mini
    role: user
    temperature: 1
    max_tokens: 15600
    frequency_penalty: 0.5
    presence_penalty: 0.5
    response_format: json_object
  reading:
    prompts:
      generate-text: |
        You are a professional German language tutor with many years of experience teaching students at different levels. 
        Please create a text in German at an {level} language level.
        The text should be interesting, clear, and appropriate for learners at this level.
        The text should be about: {topic}.
        The text must contain at least 100 tokens.
        The response must have the following JSON structure:
        {
          "level": "CEFR level here",
          "title": "Title of the text",
          "text": "Text"
        }
      rephrase-text: |
        You are an experienced German tutor with many years of experience teaching students at different levels.
        I will send you a text to analyze and complete the following tasks:
        1. Rephrase the text to avoid any plagiarism issues.
        2. Determine the CEFR level (e.g., A1, A2, B1, etc.) of the text based on its complexity, vocabulary, and grammar.
        The response must have the following JSON structure:
        {
          "level": "CEFR level here",
          "title": "Title of the text",
          "text": "Text"
        }
        Here is the text:
        {text}
      create-reading-exercise: |
        You are an experienced German tutor with many years of experience teaching students at different levels.
        I will send you a text.
        Create 10 questions related to the content of the rephrased text, along with their corresponding answers. 
        The questions should be meaningful and not easily answerable by simply rephrasing sentences from the text.
        The response must have the following JSON structure:
        {
          tasks: [
            {
              "question": "Here goes a question",
              "answer": "Here goes an answer"
            },
            {
              "question": "Here goes a question",
              "answer": "Here goes an answer"
            }
          ]
        }
        Here is the text:
        {text}
      text-to-paragraphs: |
        I will send you a text.
        Please split it into paragraphs and return them in this JSON format:
        [
          "paragraph1",
          "paragraph2",
          "paragraph3"
        ]
        Replace each paragraph with the actual text. 
        Here is the text:
        {text}