package com.ansk.development.learngermanwithansk98.integration.openai;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Chat completion choices.
 * @param index index of the choice in the list of choices
 * @param message chat completion message generated by the model
 * @param finishReason reason the model stopped generating tokens
 *
 * @author Anton Skripin
 */
public record Choice(int index,
                     Message message,
                     @JsonProperty("finish_reason") String finishReason) {
}
