name: Release Workflow

on:
  push:
    branches:
      - test_*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setting up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Building the DailyDeutsch Bot
        run: ./mvnw clean package